### ISSUE TITLE
installing from composer is not possible

### ISSUE THREAD

**Issue by skeeran** [damiandennis/yii2-scrollingblocks#1]
composer require --prefer-dist damiandennis/yii2-scrollingblocks:

Problem 1
    - Installation request for damiandennis/yii2-scrollingblocks 0.1.\* -> satisfiable by damiandennis/yii2-scrollingblocks[0.1].
    - damiandennis/yii2-scrollingblocks 0.1 requires damiandennis/wookmark-jquery dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by skeeran** [comment]
okay .. it is only possible with "dev" as minimum-stability

**Comment by shi-yang** [comment]
I also have the same problem, how did you solve it?

**Comment by skeeran** [comment]
you have to set in composer.json 

```
"minimum-stability": "dev",
```

**Comment by damiandennis** [comment]
as skeeran said you will need to add "dev" as minimum stability. This package is still under development and needs more work, just have not had the chance just yet.

**Comment by shi-yang** [comment]
okay.thanks.

**Comment by damiandennis** [comment]
added comment in 4f5e131
